    blank_issues_enabled: false
    contact_links:
      - name: Bug Report
        about: Create a report of the issue you've encountered.
        url: https://github.com/peterjuma/disasterepo/issues/new?template=bug_report.md&projects=RepoProject%2Fdisasterepo%2F1
        
